# ================== FILE .streamlit/secrets.toml ==================
# Lưu file này trong thư mục gốc dự án (cùng cấp với file streamlit app).
# Streamlit sẽ tự động nạp biến môi trường từ file này khi chạy ứng dụng.

email = "g2mms28@example.com"


OPENAI_ENDPOINT="https://aiportalapi.stu-platform.live/jpe"
OPENAI_API_KEY="sk-DXNNoBnsC6GG_GePaPVBLg"
DEPLOYMENT_NAME="gpt-4o-mini"
OPENAI_API_KEY_EMBEDDING="sk-s9oONCfC7gRPiZprWq5wfw"


# Do dùng key miễn phí lên chỉ có thể hiển thị trong khoảng thời gian 5 days
OPENWEATHERMAP_API_KEY="89fb4e8431599d5dba5e5d53a3fe4162"


# Do ko có tiền mua key lên thu thập đánh giá gợi ý sẽ sử dụng file csv
PLACES_API_KEY = "YOUR_GOOGLE_API_KEY"

CHROMA_PERSIST_DIR="data/chroma_storage"


PIXABAY_API_KEY = "52490070-f166197fd7bb7934133e669e3"


# ================== CÁCH DÙNG ==================
# 1️⃣ Tạo thư mục `.streamlit` trong project nếu chưa có.
# 2️⃣ Lưu file này với tên `secrets.toml`.
# 3️⃣ Trong code Python, truy cập bằng cách:
#    import streamlit as st
#    api_key = st.secrets["openai"]["OPENAI_API_KEY"]
# 4️⃣ Khi deploy lên Streamlit Cloud, vào tab “Secrets” và dán nội dung file này để bảo mật.
